zookeeper:
  image: jplock/zookeeper:3.4.5
  hostname: zookeeper
  ports:
    - "2181:2181"

master:
  build: .
  dockerfile: demo.Dockerfile
  command: /usr/local/sbin/mesos-master
  environment:
    - MESOS_QUORUM=1
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_LOG_DIR=/var/log
    - MESOS_ZK=zk://172.17.0.1:2181/mesos
    - MESOS_ROLES=public
  volumes:
    - /var/log/mesos:/var/log/mesos
  ports:
    - "5050:5050"

slave:
  build: .
  dockerfile: demo.Dockerfile
  net: host
  privileged: true
  command: /root/runagent
  volumes:
    - /var/log/mesos:/var/log/mesos
  environment:
    - MESOS_MASTER=zk://172.17.0.1:2181/mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_CONTAINERIZERS=mesos
    - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
    - MESOS_LOG_DIR=/var/log
    - MESOS_RESOURCES=ports(*):[9000-31100]
    - MESOS_MODULES=file:///calico/modules.json
    - MESOS_ISOLATION=com_mesosphere_mesos_NetworkIsolator
    - MESOS_HOOKS=com_mesosphere_mesos_NetworkHook
    - ETCD_AUTHORITY=172.17.0.1:4001

marathon:
  image: mesosphere/marathon:v0.14.0
  environment:
    - MARATHON_MASTER=zk://172.17.0.1:2181/mesos
    - MARATHON_ZK=zk://172.17.0.1:2181/marathon
    - MARATHON_MAX_TASKS_PER_OFFER=32
  ports:
    - "8080:8080"

etcd:
  image: quay.io/coreos/etcd:v2.0.11
  environment:
    - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379,http://etcd:4001
    - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
