FROM djosborne/mesos-modules-dev-phusion:master

RUN git remote add djosborne https://github.com/djosborne/mesos.git
RUN git fetch djosborne
RUN git checkout djosborne/strip-subnet-for-cni
RUN cd build && make -j 4 install
